### ISSUE TITLE
use catkin_make or rosbuild

### ISSUE THREAD

**Issue by Durant35** [emmjaykay/stanford_self_driving_car_code#2]
+ How to build it using rosbuild?
+ Do you think it's necessary for transferring into catkin_make build system?
    + Maybe it's usefull: [catkinTutorialsusing_rosbuild_with_catkin](http://wiki.ros.org/catkin/Tutorials/using_rosbuild_with_catkin), tried but not did
    + Chinese version: [配置ROS工作空间catkin+rosbuild](http://my.phirobot.com/blog/2013-12-overlay_catkin_and_rosbuild.html)；[catkin 与 rosbuild解析及两者区别和联系 [官方文档翻译]](http://blog.csdn.net/chishuideyu/article/details/53581013)

**Comment by Fibonacci43** [comment]
Have you got this running?

**Comment by Durant35** [comment]
Sorry for no time.

**Comment by Fibonacci43** [comment]
Thanks, anyway.
